# project-kasir
public miyaaa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbNasgor = new javax.swing.JCheckBox();
        cbmiya = new javax.swing.JCheckBox();
        cbseb = new javax.swing.JCheckBox();
        txtJlhNasgor = new javax.swing.JTextField();
        txtJlhMiya = new javax.swing.JTextField();
        txtJlhSeb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbiceT = new javax.swing.JCheckBox();
        cblemTea = new javax.swing.JCheckBox();
        cbAppleJ = new javax.swing.JCheckBox();
        txtJlhIceT = new javax.swing.JTextField();
        txtJlhLemonT = new javax.swing.JTextField();
        txtJlhApple = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtJlhBak = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbbak = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPesan = new javax.swing.JTextArea();
        jButPesan = new javax.swing.JButton();
        jButReset = new javax.swing.JButton();
        jButKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("WARUNG MAKAN YUNA");

        jLabel2.setText("Daftar Makanan :");

        jLabel3.setText("Harga :");

        jLabel4.setText("Jumlah :");

        jLabel5.setText("Daftar Minuman :");

        jLabel6.setText("Harga :");

        jLabel7.setText("Jumlah :");

        cbNasgor.setText("Nasi Goreng");
        cbNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNasgorActionPerformed(evt);
            }
        });

        cbmiya.setText("Mie Ayam");

        cbseb.setText("Seblak");
        cbseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsebActionPerformed(evt);
            }
        });

        txtJlhNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJlhNasgorActionPerformed(evt);
            }
        });

        jLabel8.setText("Rp. 13.000");

        jLabel9.setText("Rp. 13.000");

        jLabel10.setText("Rp. 17.000");

        cbiceT.setText("Ice Tea");
        cbiceT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbiceTActionPerformed(evt);
            }
        });

        cblemTea.setText("Lemon Tea");

        cbAppleJ.setText("Apple Juice");

        txtJlhLemonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJlhLemonTActionPerformed(evt);
            }
        });

        jLabel11.setText("Rp. 5.000");

        jLabel12.setText("Rp. 6.000");

        jLabel13.setText("Rp. 8.000 ");

        jLabel14.setText("Daftar Yang Dipesan :");

        jLabel15.setText("Rp. 15.000");

        cbbak.setText("Bakso");

        txtAreaPesan.setEditable(false);
        txtAreaPesan.setColumns(20);
        txtAreaPesan.setRows(5);
        jScrollPane1.setViewportView(txtAreaPesan);

        jButPesan.setText("Pesan");
        jButPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPesanActionPerformed(evt);
            }
        });

        jButReset.setText("Reset");
        jButReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButResetActionPerformed(evt);
            }
        });

        jButKeluar.setText("Keluar");
        jButKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbNasgor)
                            .addComponent(cbmiya)
                            .addComponent(cbseb)
                            .addComponent(cbbak))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtJlhSeb)
                                            .addComponent(txtJlhNasgor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJlhMiya, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbAppleJ, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbiceT)
                                            .addComponent(cblemTea))))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 17, Short.MAX_VALUE))
                                    .addComponent(txtJlhIceT)
                                    .addComponent(txtJlhLemonT)
                                    .addComponent(txtJlhApple)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtJlhBak, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel14)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButPesan)
                                .addComponent(jButReset))
                            .addComponent(jButKeluar))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNasgor)
                    .addComponent(txtJlhNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbiceT)
                    .addComponent(txtJlhIceT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmiya)
                    .addComponent(txtJlhMiya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cblemTea)
                    .addComponent(txtJlhLemonT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbseb)
                    .addComponent(txtJlhSeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbAppleJ)
                    .addComponent(txtJlhApple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJlhBak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbbak))
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButPesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButKeluar)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    }                                        

    private void cbsebActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void txtJlhNasgorActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void cbiceTActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtJlhLemonTActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jButPesanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int bayar = 0;
        if(cbNasgor.isSelected()){
            int jumlah=Integer.parseInt(txtJlhNasgor.getText());
            int total;
            total=jumlah*13000;
            bayar=bayar+total;
            tampil +=cbNasgor.getText()+" Rp. 13000"+" x "+jumlah+" = "+total+"\n";    
        }if(cbmiya.isSelected()){
            int jumlah=Integer.parseInt(txtJlhMiya.getText());
            int total;
            total=jumlah*13000;
            bayar=bayar+total;
            tampil +=cbmiya.getText()+" Rp. 13000"+" x "+jumlah+" = "+total+"\n";
        }if(cbseb.isSelected()){
            int jumlah=Integer.parseInt(txtJlhSeb.getText());
            int total;
            total=jumlah*17000;
            bayar=bayar+total;
            tampil +=cbseb.getText()+" Rp. 17000"+" x "+jumlah+" = "+total+"\n";
        }if(cbbak.isSelected()){
            int jumlah=Integer.parseInt(txtJlhBak.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil +=cbbak.getText()+" Rp. 15000"+" x "+jumlah+" = "+total+"\n";
        }if(cbiceT.isSelected()){
            int jumlah=Integer.parseInt(txtJlhIceT.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil +=cbiceT.getText()+" Rp. 5000"+" x "+jumlah+" = "+total+"\n";
        }if(cblemTea.isSelected()){
            int jumlah=Integer.parseInt(txtJlhLemonT.getText());
            int total;
            total=jumlah*6000;
            bayar=bayar+total;
            tampil +=cblemTea.getText()+" Rp. 6000"+" x "+jumlah+" = "+total+"\n";
        }if(cbAppleJ.isSelected()){
            int jumlah=Integer.parseInt(txtJlhApple.getText());
            int total;
            total=jumlah*8000;
            bayar=bayar+total;
            tampil +=cbAppleJ.getText()+" Rp. 8000"+" x "+jumlah+" = "+total+"\n";
        }
        txtAreaPesan.setText(tampil+"============================="+"\n"+"Total Bayar ="+bayar);
        
    }                                         

    private void jButResetActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here: 
        cbNasgor.setSelected(false);
        cbmiya.setSelected(false);
        cbseb.setSelected(false);
        cbbak.setSelected(false);
        cbiceT.setSelected(false);
        cblemTea.setSelected(false);
        cbAppleJ.setSelected(false);
        
        txtJlhNasgor.setText("");
        txtJlhMiya.setText("");
        txtJlhSeb.setText("");
        txtJlhBak.setText("");
        txtJlhIceT.setText("");
        txtJlhLemonT.setText("");
        txtJlhApple.setText("");
        
        txtAreaPesan.setText("");
    }                                         

    private void jButKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        dispose();
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miyaaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miyaaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miyaaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miyaaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miyaaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox cbAppleJ;
    private javax.swing.JCheckBox cbNasgor;
    private javax.swing.JCheckBox cbbak;
    private javax.swing.JCheckBox cbiceT;
    private javax.swing.JCheckBox cblemTea;
    private javax.swing.JCheckBox cbmiya;
    private javax.swing.JCheckBox cbseb;
    private javax.swing.JButton jButKeluar;
    private javax.swing.JButton jButPesan;
    private javax.swing.JButton jButReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaPesan;
    private javax.swing.JTextField txtJlhApple;
    private javax.swing.JTextField txtJlhBak;
    private javax.swing.JTextField txtJlhIceT;
    private javax.swing.JTextField txtJlhLemonT;
    private javax.swing.JTextField txtJlhMiya;
    private javax.swing.JTextField txtJlhNasgor;
    private javax.swing.JTextField txtJlhSeb;
    // End of variables declaration                   
}
